### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [AdrianArroyoCalle/ama#1]
Editor, terminal, tools, themes, fonts, process, etc.

**Comment by AdrianArroyoCalle** [comment]
Editor: Geany, trying to move to a more advanced editor like Atom or VS Code
Terminal: Gnome Terminal with Bash. Once I installed zsh but I didn't see too much benefits on it.
Tools: Node.js/Npm, Jekyll, ImageMagick ( I love it), CMake, Rust and C++ compilers. I use Git but I have some projects using Plastic SCM. VMware is my favourite virtual machine.
Themes: I don't like to search themes for nothing so I always use the default styles. With Ubuntu I used Unity as is (I don't know why people hate it).
OS: For development I always use Linux if possible. I started with Ubuntu and I liked it. I've tried openSUSE, Fedora, Arch and NetBSD but I still use Ubuntu (currently Lubuntu). On Microsoft side I have Windows 7 with Visual Studio 2010 if I need to port something.
Browser: Firefox!
Fonts: Nothing special.

I hope I didn't forget something
