### ISSUE TITLE
What excites you most about the future of the web?

### ISSUE THREAD

**Issue by sindresorhus** [AdrianArroyoCalle/ama#4]

**Comment by AdrianArroyoCalle** [comment]
WebGL + WebAudio + WebWorkers + WebSockets + WebAssembly + IndexedDB = Great experience!
WebGL, WebAudio and WebSockets are already fine. WebWorkers should change our thinking, APIs that only run on WebWorkers like IndexedDB-sync API is the way to go. IndexedDB hasn't been used too much yet to see how important is. If WebAssembly is going to be like Emscripten but better then it's going to be amazing.
