### ISSUE TITLE
What's your view of New Zealand?

### ISSUE THREAD

**Issue by Widdershin** [AdrianArroyoCalle/ama#6]

**Comment by AdrianArroyoCalle** [comment]
I haven't been in New Zeland (too far!!). So I know there are two main islands (north and south), you're changing your flag, there's so much natural beauty and the haka dance (once I saw the dance from a New Zeland's participants in a sport event (orienteering)). Ah, there's also the Kim Dotcom mansion. I think that you're a quietly country, quieter than Australia, I don't know exactly why.
