### ISSUE TITLE
Being a polyglot engineer

### ISSUE THREAD

**Issue by blainsmith** [AdrianArroyoCalle/ama#8]
Do you find that being a polyglot engineer makes you better at your job? Does your job require you to be that way or do you have a personal interest in trying new languages?

**Comment by AdrianArroyoCalle** [comment]
Well, I'm still a student. I know Spanish (as first language) and English. English is important, very important. There are a lot of things which aren't translated, even more in technology. Spanish is the second language by number of speakers and while I think it's more elegant and poetic than English you will miss lot of things from 21st century world. Also English-centric people domination in technology is easy to see. Two examples: 
 - Keyboard layout. Spain uses QWERTY and letters are in the same position (with Ñ and Ç) but other symbols like / + = { } [ ] . ; ´ < > are in different position. When I install a new OS sometimes the keyboard layout doesn't configure OR it doesn't configure well (tty working, X11 not).
- Writing my name. It's incredible that in a lot of forms around the web I can't put my name "Adrián". Also, sometimes the form doesn't catch the problem and I receive a package from internet with a funny missing symbol encoding error printed in the consignee.

People in Spain must study English and a second language (you can quit the second language after two years). The second language isn't specified but my high school offers French or German. Other high schools offer Portuguese and Chinese. I studied French at school and I went a week to France with a exchange partner. It's easier than English for most people and you get a better level in less time (fun fact, my French teacher learnt Esperanto when she was young). Then I stop studying French beacuse I was bored (my subject with less marks).

I have a friend who is learning Japanese right now, two Russian friends, a friend learning Catalan, my aunt is learning Chinese. I'm interested in Chinese, but I'm going to wait until my English improves.

PD: Interesting fact. You might know that USA films and series voices are translated here. The Simpsons has two translations: Spain and Latin America. They're so different (Homer in Spain, Homero in Latin America) that YouTube videos about Simpsons are always a flame war about your preferred translation.

PD2: In a summer camp in Madrid we were people from Castilla y León and from Euskadi. Euskadi people learn Euskera and Spanish at school. They talked between then in Euskera, we didn't know what they were saying, even on group games. These is interesting if you consider that we live in the same country, same zone (north Spain).
