### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [AdrianArroyoCalle/ama#9]

**Comment by AdrianArroyoCalle** [comment]
No. I know people who goes to courses and they tell me things about it. Once I had the opportunity to go to a leadership campus in Toledo (Spain) but I had to do another things the same week. What about you @jedireza?

**Comment by jedireza** [comment]
Yes, I help organize the [NodeSchool San Francisco](http://nodeschool.io/sanfrancisco/) chapter.
